# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminLoginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1600, 900)
        Widget.setMinimumSize(QtCore.QSize(800, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./image/searchIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Widget.setWindowIcon(icon)
        Widget.setStyleSheet("/**\n"
"    该页面为浅紫色皮肤\n"
"*/\n"
"#frame_background{\n"
"border-image:url(:/image/background-3.png);\n"
"}\n"
"\n"
"#frame_login{background-color:#ffffff}\n"
"\n"
"#frame_user_name,#frame_pwd{\n"
"    border: 1px solid #696969;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"#btn_Return{\n"
"    border:none;\n"
"    color:#7185ff;\n"
"}\n"
"\n"
"\n"
"#btn_Return:hover{\n"
"    border:none;\n"
"    color:#7185ff;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"}\n"
"\n"
"#btn_login{\n"
"    color:#ffffff;\n"
"    border: none;\n"
"    background-color:#8293fd;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_login:hover{\n"
"    color:#ffffff;\n"
"    border: none;\n"
"    background-color:#4861fb;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#Btn_login:pressed{\n"
"    color:#ffffff;\n"
"    border: none;\n"
"    background-color:#8293fd;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#label_login\n"
"{\n"
"    color:#7185ff;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.gridLayout_6 = QtWidgets.QGridLayout(Widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_background = QtWidgets.QFrame(Widget)
        self.frame_background.setStyleSheet("")
        self.frame_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_background.setObjectName("frame_background")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_background)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.frame_background)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_login = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_login.sizePolicy().hasHeightForWidth())
        self.frame_login.setSizePolicy(sizePolicy)
        self.frame_login.setMinimumSize(QtCore.QSize(500, 600))
        self.frame_login.setMaximumSize(QtCore.QSize(500, 600))
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_login)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_login = QtWidgets.QLabel(self.frame_login)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.horizontalLayout.addWidget(self.label_login)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.frame_user_name = QtWidgets.QFrame(self.frame_login)
        self.frame_user_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user_name.setObjectName("frame_user_name")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_user_name)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.label_user_name = QtWidgets.QLabel(self.frame_user_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_name.sizePolicy().hasHeightForWidth())
        self.label_user_name.setSizePolicy(sizePolicy)
        self.label_user_name.setMinimumSize(QtCore.QSize(30, 30))
        self.label_user_name.setMaximumSize(QtCore.QSize(30, 30))
        self.label_user_name.setStyleSheet("border-image: url(:/image/user_name.png);")
        self.label_user_name.setText("")
        self.label_user_name.setObjectName("label_user_name")
        self.horizontalLayout_11.addWidget(self.label_user_name)
        self.lineE_user_name = QtWidgets.QLineEdit(self.frame_user_name)
        self.lineE_user_name.setObjectName("lineE_user_name")
        self.horizontalLayout_11.addWidget(self.lineE_user_name)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.frame_user_name)
        spacerItem8 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem9 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.frame_pwd = QtWidgets.QFrame(self.frame_login)
        self.frame_pwd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pwd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pwd.setObjectName("frame_pwd")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_pwd)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.label_pwd = QtWidgets.QLabel(self.frame_pwd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pwd.sizePolicy().hasHeightForWidth())
        self.label_pwd.setSizePolicy(sizePolicy)
        self.label_pwd.setMinimumSize(QtCore.QSize(30, 30))
        self.label_pwd.setMaximumSize(QtCore.QSize(30, 30))
        self.label_pwd.setStyleSheet("border-image: url(:/image/pwd.png);")
        self.label_pwd.setText("")
        self.label_pwd.setObjectName("label_pwd")
        self.horizontalLayout_3.addWidget(self.label_pwd)
        self.password = QtWidgets.QLineEdit(self.frame_pwd)
        self.password.setObjectName("password")
        self.horizontalLayout_3.addWidget(self.password)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_pwd)
        spacerItem12 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.btn_Return = QtWidgets.QPushButton(self.frame_login)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(True)
        self.btn_Return.setFont(font)
        self.btn_Return.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Return.setObjectName("btn_Return")
        self.horizontalLayout_5.addWidget(self.btn_Return)
        spacerItem14 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.btn_login = QtWidgets.QPushButton(self.frame_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(320, 50))
        self.btn_login.setMaximumSize(QtCore.QSize(320, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_login.setStyleSheet("#label_pwd\n"
"{\n"
"    border-image:url(VacantClassrooms-master/image/pwd.png);\n"
"\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_6.addWidget(self.btn_login)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem18 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem19, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_login)
        self.frame_pic = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pic.sizePolicy().hasHeightForWidth())
        self.frame_pic.setSizePolicy(sizePolicy)
        self.frame_pic.setMinimumSize(QtCore.QSize(500, 600))
        self.frame_pic.setStyleSheet("background-image: url(:/image/3.png);")
        self.frame_pic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pic.setObjectName("frame_pic")
        self.horizontalLayout_8.addWidget(self.frame_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem21 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem21)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_background, 0, 0, 1, 1)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "管理员登录界面"))
        self.label_login.setText(_translate("Widget", "BUPT"))
        self.btn_Return.setText(_translate("Widget", "   Return   "))
        self.btn_login.setText(_translate("Widget", "Login"))
