# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1600, 900)
        Widget.setMinimumSize(QtCore.QSize(800, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/searchIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Widget.setWindowIcon(icon)
        Widget.setStyleSheet("#frame_background{\n"
"border-image:url(:/image/background-3.png);\n"
"}\n"
"\n"
"#frame_login{background-color:#ffffff}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_background = QtWidgets.QFrame(Widget)
        self.frame_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_background.setObjectName("frame_background")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_background)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.c1 = QtWidgets.QPushButton(self.frame_background)
        self.c1.setMinimumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.c1.setFont(font)
        self.c1.setStyleSheet("QPushButton#c1 {\n"
"        background-color: rgb(255, 138, 140);\n"
"        border: 2px groove gray;\n"
"        border-radius: 10px;\n"
"         padding: 2px 4px;\n"
"        border-style: outset;\n"
"    }\n"
"\n"
"    QPushButton#c1:hover {\n"
"        background-color: rgb(229, 241, 251);\n"
"    }\n"
"\n"
"\n"
"QPushButton#c1 {\n"
"        color: blue;\n"
"        font-weight: bold;\n"
"        text-stroke: 1px black;\n"
"    }\n"
"\n"
"QPushButton#c1:checked {\n"
"        background-color: rgb(170, 0, 0);\n"
"    }")
        self.c1.setCheckable(True)
        self.c1.setObjectName("c1")
        self.horizontalLayout_2.addWidget(self.c1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.c2 = QtWidgets.QPushButton(self.frame_background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c2.sizePolicy().hasHeightForWidth())
        self.c2.setSizePolicy(sizePolicy)
        self.c2.setMinimumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.c2.setFont(font)
        self.c2.setStyleSheet("QPushButton#c2 {\n"
"        background-color: rgb(255, 138, 140);\n"
"        border: 2px groove gray;\n"
"        border-radius: 10px;\n"
"         padding: 2px 4px;\n"
"        border-style: outset;\n"
"    }\n"
"\n"
"    QPushButton#c2:hover {\n"
"        background-color: rgb(229, 241, 251);\n"
"    }\n"
"\n"
"\n"
"QPushButton#c2 {\n"
"        color: blue;\n"
"        font-weight: bold;\n"
"        text-stroke: 1px black;\n"
"    }\n"
"\n"
"QPushButton#c2:checked {\n"
"        background-color: rgb(170, 0, 0);\n"
"    }")
        self.c2.setCheckable(True)
        self.c2.setObjectName("c2")
        self.horizontalLayout_2.addWidget(self.c2)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.c3 = QtWidgets.QPushButton(self.frame_background)
        self.c3.setMinimumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.c3.setFont(font)
        self.c3.setStyleSheet("QPushButton#c3 {\n"
"        background-color: rgb(255, 138, 140);\n"
"        border: 2px groove gray;\n"
"        border-radius: 10px;\n"
"         padding: 2px 4px;\n"
"        border-style: outset;\n"
"    }\n"
"\n"
"    QPushButton#c3:hover {\n"
"        background-color: rgb(229, 241, 251);\n"
"    }\n"
"\n"
"\n"
"QPushButton#c3 {\n"
"        color: blue;\n"
"        font-weight: bold;\n"
"        text-stroke: 1px black;\n"
"    }\n"
"\n"
"QPushButton#c3:checked {\n"
"        background-color: rgb(170, 0, 0);\n"
"    }")
        self.c3.setCheckable(True)
        self.c3.setObjectName("c3")
        self.horizontalLayout_2.addWidget(self.c3)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.c4 = QtWidgets.QPushButton(self.frame_background)
        self.c4.setMinimumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.c4.setFont(font)
        self.c4.setStyleSheet("QPushButton#c4 {\n"
"        background-color: rgb(255, 138, 140);\n"
"        border: 2px groove gray;\n"
"        border-radius: 10px;\n"
"         padding: 2px 4px;\n"
"        border-style: outset;\n"
"    }\n"
"\n"
"    QPushButton#c4:hover {\n"
"        background-color: rgb(229, 241, 251);\n"
"    }\n"
"\n"
"\n"
"QPushButton#c4 {\n"
"        color: blue;\n"
"        font-weight: bold;\n"
"        text-stroke: 1px black;\n"
"    }\n"
"\n"
"QPushButton#c4:checked {\n"
"        background-color: rgb(170, 0, 0);\n"
"    }")
        self.c4.setCheckable(True)
        self.c4.setObjectName("c4")
        self.horizontalLayout_2.addWidget(self.c4)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_background)
        self.pushButton_5.setMinimumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5 {\n"
"        background-color: rgb(255, 138, 140);\n"
"        border: 2px groove gray;\n"
"        border-radius: 10px;\n"
"         padding: 2px 4px;\n"
"        border-style: outset;\n"
"    }\n"
"\n"
"    QPushButton#pushButton_5:hover {\n"
"        background-color: rgb(229, 241, 251);\n"
"        color: black;\n"
"    }\n"
"\n"
"    QPushButton#pushButton_5:pressed {\n"
"        background-color: rgb(204, 228, 247);\n"
"        border-style: inset;\n"
"    }\n"
"\n"
"QPushButton#pushButton_5 {\n"
"        color: blue;\n"
"        font-weight: bold;\n"
"        text-stroke: 1px black;\n"
"    }\n"
"")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.Btn_feedback = QtWidgets.QPushButton(self.frame_background)
        self.Btn_feedback.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_feedback.setFont(font)
        self.Btn_feedback.setStyleSheet("QPushButton#Btn_feedback {\n"
"        background-color: rgb(255, 138, 140);\n"
"        border: 2px groove gray;\n"
"        border-radius: 10px;\n"
"         padding: 2px 4px;\n"
"        border-style: outset;\n"
"    }\n"
"\n"
"    QPushButton#Btn_feedback:hover {\n"
"        background-color: rgb(229, 241, 251);\n"
"        color: black;\n"
"    }\n"
"\n"
"    QPushButton#Btn_feedback:pressed {\n"
"        background-color: rgb(204, 228, 247);\n"
"        border-style: inset;\n"
"    }\n"
"\n"
"QPushButton#Btn_feedback {\n"
"        color: blue;\n"
"        font-weight: bold;\n"
"        text-stroke: 1px black;\n"
"    }\n"
"")
        self.Btn_feedback.setObjectName("Btn_feedback")
        self.horizontalLayout_2.addWidget(self.Btn_feedback)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.frame = QtWidgets.QFrame(self.frame_background)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_login = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_login.sizePolicy().hasHeightForWidth())
        self.frame_login.setSizePolicy(sizePolicy)
        self.frame_login.setMinimumSize(QtCore.QSize(500, 600))
        self.frame_login.setMaximumSize(QtCore.QSize(500, 600))
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_login)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.label_login = QtWidgets.QLabel(self.frame_login)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("#label_login\n"
"{\n"
"    color:#7185ff;\n"
"\n"
"}")
        self.label_login.setObjectName("label_login")
        self.horizontalLayout.addWidget(self.label_login)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame__time = QtWidgets.QFrame(self.frame_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame__time.sizePolicy().hasHeightForWidth())
        self.frame__time.setSizePolicy(sizePolicy)
        self.frame__time.setMinimumSize(QtCore.QSize(480, 480))
        self.frame__time.setMaximumSize(QtCore.QSize(480, 480))
        self.frame__time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame__time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame__time.setObjectName("frame__time")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame__time)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.frame__time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(400, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 4, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 4, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 4, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 3, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame__time)
        spacerItem11 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem12 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_login)
        self.frame_pic = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_pic.sizePolicy().hasHeightForWidth())
        self.frame_pic.setSizePolicy(sizePolicy)
        self.frame_pic.setMinimumSize(QtCore.QSize(500, 600))
        self.frame_pic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pic.setObjectName("frame_pic")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_pic)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 521, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(400, 600))
        self.tableWidget.setMaximumSize(QtCore.QSize(600, 600))
        self.tableWidget.setStyleSheet("#tableWidget{ background-color: #aaaaff; }\n"
"/* 设置表格的基本样式 */  \n"
"QTableView {  \n"
"border-image:url(:/res/pic/background-1.png);\n"
"    background-color: #f9f9f9; /* 背景色 */  \n"
"    border: 2px solid #a1a1a1; /* 边框 */  \n"
"    gridline-color: #e0e0e0; /* 网格线颜色 */  \n"
"    selection-background-color: #88d8b0; /* 选中项背景色 */  \n"
"    selection-color: #ffffff; /* 选中项文字颜色 */  \n"
"}  \n"
"  \n"
"/* 设置表头样式 */  \n"
"QHeaderView::section {  \n"
"    background-color: #f0a3a3; /* 背景色 */  \n"
"    color: #ffffff; /* 文字颜色 */  \n"
"    border: 1px solid #a1a1a1; /* 边框 */  \n"
"    border-bottom: 2px solid #a1a1a1; /* 底边框加粗 */  \n"
"    padding: 4px; /* 内边距 */  \n"
"    font-weight: bold; /* 字体加粗 */  \n"
"}  \n"
"  \n"
"/* 设置表格项的样式 */  \n"
"QTableView::item {  \n"
"    border: none; /* 无边框 */  \n"
"    padding: 4px; /* 内边距 */  \n"
"    background-color: transparent; \n"
"}  \n"
"  \n"
"/* 奇数行样式 */  \n"
"QTableView::item:nth-child(odd) {  \n"
"    background-color: #e9e9e9; /* 奇数行背景色 */  \n"
"}  \n"
"  \n"
"/* 偶数行样式 */  \n"
"QTableView::item:nth-child(even) {  \n"
"    background-color: #f5f5f5; /* 偶数行背景色 */  \n"
"}  \n"
"  \n"
"/* 鼠标悬停时的样式 */  \n"
"QTableView::item:hover {  \n"
"    background-color: #c8e6c9; /* 鼠标悬停时的背景色 */  \n"
"}  \n"
"  \n"
"/* 选中项的样式（当与selection-background-color不同时使用）*/  \n"
"QTableView::item:selected {  \n"
"    background-color: #a5d6a7; /* 选中项背景色 */  \n"
"}  \n"
"  \n"
"/* 自定义滚动条样式 */  \n"
"QScrollBar:vertical {  \n"
"    border: none; /* 无边框 */  \n"
"    background: #f0f0f0; /* 背景色 */  \n"
"    width: 15px; /* 宽度 */  \n"
"    margin: 0px 0px 0px 0px; /* 边距 */  \n"
"}  \n"
"  \n"
"QScrollBar::handle:vertical {  \n"
"    background: #a8a8a8; /* 滑块背景色 */  \n"
"    min-height: 20px; /* 最小高度 */  \n"
"}  \n"
"  \n"
"QScrollBar::add-line:vertical {  \n"
"    border: none; /* 无边框 */  \n"
"    background: none; /* 无背景 */  \n"
"    height: 0px; /* 高度 */  \n"
"    subcontrol-position: bottom; /* 位置 */  \n"
"    subcontrol-origin: margin; /* 起始位置 */  \n"
"}  \n"
"  \n"
"QScrollBar::sub-line:vertical {  \n"
"    border: none; /* 无边框 */  \n"
"    background: none; /* 无背景 */  \n"
"    height: 0px; /* 高度 */  \n"
"    subcontrol-position: top; /* 位置 */  \n"
"    subcontrol-origin: margin; /* 起始位置 */  \n"
"}  \n"
"  \n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {  \n"
"    border: none; /* 无边框 */  \n"
"    background: none; /* 无背景 */  \n"
"    height: 0px; /* 高度 */  \n"
"}  \n"
"  \n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {  \n"
"    background: none; /* 无背景 */  \n"
"}\n"
"\n"
"")
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_8.addWidget(self.frame_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem14 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.frame_background)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "空教室查询系统主界面"))
        self.c1.setText(_translate("Widget", "教1"))
        self.c2.setText(_translate("Widget", "教2"))
        self.c3.setText(_translate("Widget", "教3"))
        self.c4.setText(_translate("Widget", "教4"))
        self.pushButton_5.setText(_translate("Widget", "全选"))
        self.Btn_feedback.setText(_translate("Widget", "教室空闲情况反馈"))
        self.label_login.setText(_translate("Widget", "Time"))
        self.pushButton_9.setText(_translate("Widget", "10:40-11:25"))
        self.pushButton_11.setText(_translate("Widget", "13:00-13:45"))
        self.pushButton_18.setText(_translate("Widget", "19:20-20:05"))
        self.pushButton_7.setText(_translate("Widget", "8:50-9:35"))
        self.pushButton_6.setText(_translate("Widget", "8:00-8:45"))
        self.pushButton_19.setText(_translate("Widget", "20:10-20:55"))
        self.pushButton_16.setText(_translate("Widget", "17:25-18:10"))
        self.pushButton_17.setText(_translate("Widget", "18:30-19:15"))
        self.pushButton_10.setText(_translate("Widget", "11:30-12:15"))
        self.pushButton_8.setText(_translate("Widget", "9:50-10:35"))
        self.pushButton_13.setText(_translate("Widget", "14:45-15:30"))
        self.pushButton_20.setText(_translate("Widget", "全选"))
        self.pushButton_15.setText(_translate("Widget", "16:35-17:20"))
        self.pushButton_14.setText(_translate("Widget", "15:40-16:25"))
        self.pushButton_12.setText(_translate("Widget", "13:50-14:35"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "教室"))
